sudo: true
dist: xenial

language: go

go:
- "1.10"

git:
  depth: 1

notifications:
  email: false

env:
- DEP_VERSION="0.5.0"

before_install:
- wget https://github.com/ethereum/solidity/releases/download/v0.4.18/solidity-ubuntu-trusty.zip
- unzip -o solidity-ubuntu-trusty.zip -d $GOPATH/bin
- sudo apt-get install libz3-dev -y
- curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
- dep ensure
- go get github.com/SmartMeshFoundation/Spectrum/cmd/abigen
- go generate github.com/SmartMeshFoundation/SmartPlasma/solidity

install: true

script:
- go test ./...