language: go

go:
- "1.10"
- md-checkpoint

git:
  depth: 1

notifications:
  email: false

env:
- DEP_VERSION="0.5.0"

before_install:
- curl -L -s https://github.com/golang/dep/releases/download/v${DEP_VERSION}/dep-linux-amd64 -o $GOPATH/bin/dep
- chmod +x $GOPATH/bin/dep
- sudo add-apt-repository ppa:ethereum/ethereum -y
- sudo apt-get update -y
- sudo apt-get install solc -y

install:
  go get -t ./...
- dep ensure
- go get github.com/ethereum/go-ethereum/cmd/abigen
- go generate github.com/SmartMeshFoundation/SmartPlasma/solidity

script:
- go test -v ./...